name: Test, Build, Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency: preview-${{ github.ref }}
env:
  PUBLIC_URL: /CrankBit-FrontEnd/pr-preview/pr-${{ github.event.number }}
permissions:
  contents: write
  pull-requests: write
jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install and Build
        run: |
          yarn
          yarn pre-commit
          yarn build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
